# Generated by Django 4.1.7 on 2023-02-24 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0002_member"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="requests",
            name="sender_IP",
        ),
        migrations.DeleteModel(
            name="Member",
        ),
    ]
