# Generated by Django 4.1.7 on 2023-02-27 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0003_remove_requests_sender_ip_delete_member"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Requests",
            new_name="Request",
        ),
        migrations.AlterModelOptions(
            name="request",
            options={"ordering": ["-timestamp"]},
        ),
        migrations.AddIndex(
            model_name="request",
            index=models.Index(
                fields=["-timestamp"], name="rooms_reque_timesta_326da9_idx"
            ),
        ),
    ]
